// <auto-generated />
namespace work_02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StockManagementScript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockManagementScript));
        
        string IMigrationMetadata.Id
        {
            get { return "202306141441196_StockManagementScript"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
